// ICD-10-GM (deutsche Ausgabe, für Österreich gültig)
// Vollständiges F-Kapitel (Psychische und Verhaltensstörungen) + häufige andere Kapitel

export interface ICD10Code {
  code: string
  label: string
  chapter: string
  definition?: string
}

export const ICD10_CODES: ICD10Code[] = [
// ── F00–F09 Organische psychische Störungen ──────────────────────────────────
  { code: 'F00', label: 'Demenz bei Alzheimer-Krankheit', chapter: 'F' },
  { code: 'F00.0', label: 'Demenz bei Alzheimer-Krankheit, mit frühem Beginn', chapter: 'F' },
  { code: 'F00.1', label: 'Demenz bei Alzheimer-Krankheit, mit spätem Beginn', chapter: 'F' },
  { code: 'F00.2', label: 'Demenz bei Alzheimer-Krankheit, atypische oder gemischte Form', chapter: 'F' },
  { code: 'F01', label: 'Vaskuläre Demenz', chapter: 'F' },
  { code: 'F01.0', label: 'Vaskuläre Demenz mit akutem Beginn', chapter: 'F' },
  { code: 'F01.1', label: 'Multiinfarkt-Demenz', chapter: 'F' },
  { code: 'F01.2', label: 'Subkortikale vaskuläre Demenz', chapter: 'F' },
  { code: 'F02', label: 'Demenz bei andernorts klassifizierten Krankheiten', chapter: 'F' },
  { code: 'F03', label: 'Nicht näher bezeichnete Demenz', chapter: 'F' },
  { code: 'F04', label: 'Organisches amnestisches Syndrom', chapter: 'F' },
  { code: 'F05', label: 'Delir, nicht durch Alkohol oder andere psychotrope Substanzen bedingt', chapter: 'F' },
  { code: 'F06', label: 'Andere psychische Störungen aufgrund einer Schädigung oder Funktionsstörung des Gehirns', chapter: 'F' },
  { code: 'F06.0', label: 'Organische Halluzinose', chapter: 'F' },
  { code: 'F06.1', label: 'Organische katatone Störung', chapter: 'F' },
  { code: 'F06.2', label: 'Organische wahnhafte (schizophreniforme) Störung', chapter: 'F' },
  { code: 'F06.3', label: 'Organische affektive Störungen', chapter: 'F' },
  { code: 'F06.4', label: 'Organische Angststörung', chapter: 'F' },
  { code: 'F06.5', label: 'Organische dissoziative Störung', chapter: 'F' },
  { code: 'F06.6', label: 'Organische emotional labile (asthenische) Störung', chapter: 'F' },
  { code: 'F07', label: 'Persönlichkeits- und Verhaltensstörung aufgrund einer Krankheit, Schädigung oder Funktionsstörung des Gehirns', chapter: 'F' },
  { code: 'F09', label: 'Nicht näher bezeichnete organische oder symptomatische psychische Störung', chapter: 'F' },

// ── F10–F19 Substanzbedingte Störungen ───────────────────────────────────────
  { code: 'F10', label: 'Psychische und Verhaltensstörungen durch Alkohol', chapter: 'F' },
  { code: 'F10.0', label: 'Akute Alkoholintoxikation', chapter: 'F' },
  { code: 'F10.1', label: 'Schädlicher Gebrauch von Alkohol', chapter: 'F' },
  { code: 'F10.2', label: 'Alkoholabhängigkeitssyndrom', chapter: 'F' },
  { code: 'F10.3', label: 'Alkoholentzugssyndrom', chapter: 'F' },
  { code: 'F10.4', label: 'Alkoholentzugssyndrom mit Delir', chapter: 'F' },
  { code: 'F11', label: 'Psychische und Verhaltensstörungen durch Opioide', chapter: 'F' },
  { code: 'F11.1', label: 'Schädlicher Gebrauch von Opioiden', chapter: 'F' },
  { code: 'F11.2', label: 'Opioidabhängigkeitssyndrom', chapter: 'F' },
  { code: 'F12', label: 'Psychische und Verhaltensstörungen durch Cannabinoide', chapter: 'F' },
  { code: 'F12.1', label: 'Schädlicher Gebrauch von Cannabinoiden', chapter: 'F' },
  { code: 'F12.2', label: 'Cannabinoidabhängigkeitssyndrom', chapter: 'F' },
  { code: 'F13', label: 'Psychische und Verhaltensstörungen durch Sedativa oder Hypnotika', chapter: 'F' },
  { code: 'F14', label: 'Psychische und Verhaltensstörungen durch Kokain', chapter: 'F' },
  { code: 'F15', label: 'Psychische und Verhaltensstörungen durch andere Stimulanzien', chapter: 'F' },
  { code: 'F16', label: 'Psychische und Verhaltensstörungen durch Halluzinogene', chapter: 'F' },
  { code: 'F17', label: 'Psychische und Verhaltensstörungen durch Tabak', chapter: 'F' },
  { code: 'F17.1', label: 'Schädlicher Gebrauch von Tabak', chapter: 'F' },
  { code: 'F17.2', label: 'Tabakabhängigkeitssyndrom', chapter: 'F' },
  { code: 'F18', label: 'Psychische und Verhaltensstörungen durch flüchtige Lösungsmittel', chapter: 'F' },
  { code: 'F19', label: 'Psychische und Verhaltensstörungen durch mehrere Substanzen', chapter: 'F' },

// ── F20–F29 Schizophrenie und verwandte Störungen ────────────────────────────
  { code: 'F20', label: 'Schizophrenie', chapter: 'F' },
  { code: 'F20.0', label: 'Paranoide Schizophrenie', chapter: 'F', definition: "Paranoide Schizophrenie: Dominiert von Verfolgungswahn, Beziehungswahn oder anderen Wahnformen sowie akustischen Halluzinationen." },
  { code: 'F20.1', label: 'Hebephrene Schizophrenie', chapter: 'F' },
  { code: 'F20.2', label: 'Katatone Schizophrenie', chapter: 'F' },
  { code: 'F20.3', label: 'Undifferenzierte Schizophrenie', chapter: 'F' },
  { code: 'F20.4', label: 'Postschizophrene Depression', chapter: 'F' },
  { code: 'F20.5', label: 'Schizophrenes Residuum', chapter: 'F' },
  { code: 'F20.6', label: 'Schizophrenia simplex', chapter: 'F' },
  { code: 'F21', label: 'Schizotype Störung', chapter: 'F' },
  { code: 'F22', label: 'Anhaltende wahnhafte Störungen', chapter: 'F' },
  { code: 'F22.0', label: 'Wahnhafte Störung', chapter: 'F' },
  { code: 'F23', label: 'Akute vorübergehende psychotische Störungen', chapter: 'F' },
  { code: 'F24', label: 'Induzierte wahnhafte Störung', chapter: 'F' },
  { code: 'F25', label: 'Schizoaffektive Störungen', chapter: 'F' },
  { code: 'F25.0', label: 'Schizoaffektive Störung, gegenwärtig manisch', chapter: 'F' },
  { code: 'F25.1', label: 'Schizoaffektive Störung, gegenwärtig depressiv', chapter: 'F' },
  { code: 'F25.2', label: 'Gemischte schizoaffektive Störung', chapter: 'F' },
  { code: 'F28', label: 'Sonstige nichtorganische psychotische Störungen', chapter: 'F' },
  { code: 'F29', label: 'Nicht näher bezeichnete nichtorganische Psychose', chapter: 'F' },

// ── F30–F39 Affektive Störungen ──────────────────────────────────────────────
  { code: 'F30', label: 'Manische Episode', chapter: 'F' },
  { code: 'F30.0', label: 'Hypomanie', chapter: 'F' },
  { code: 'F30.1', label: 'Manie ohne psychotische Symptome', chapter: 'F' },
  { code: 'F30.2', label: 'Manie mit psychotischen Symptomen', chapter: 'F' },
  { code: 'F31', label: 'Bipolare affektive Störung', chapter: 'F' },
  { code: 'F31.0', label: 'Bipolare affektive Störung, gegenwärtig hypomanische Episode', chapter: 'F' },
  { code: 'F31.1', label: 'Bipolare affektive Störung, gegenwärtig manische Episode ohne psychotische Symptome', chapter: 'F' },
  { code: 'F31.2', label: 'Bipolare affektive Störung, gegenwärtig manische Episode mit psychotischen Symptomen', chapter: 'F' },
  { code: 'F31.3', label: 'Bipolare affektive Störung, gegenwärtig leichte oder mittelgradige depressive Episode', chapter: 'F', definition: "Bipolare affektive Störung, depressive Episode: Frühere manische oder hypomane Episode in der Vorgeschichte, aktuell depressive Symptomatik." },
  { code: 'F31.4', label: 'Bipolare affektive Störung, gegenwärtig schwere depressive Episode ohne psychotische Symptome', chapter: 'F' },
  { code: 'F31.5', label: 'Bipolare affektive Störung, gegenwärtig schwere depressive Episode mit psychotischen Symptomen', chapter: 'F' },
  { code: 'F31.6', label: 'Bipolare affektive Störung, gegenwärtig gemischte Episode', chapter: 'F' },
  { code: 'F31.7', label: 'Bipolare affektive Störung, gegenwärtig remittiert', chapter: 'F' },
  { code: 'F32', label: 'Depressive Episode', chapter: 'F' },
  { code: 'F32.0', label: 'Leichte depressive Episode', chapter: 'F', definition: "Leichte depressive Episode mit typischen Symptomen wie gedrückte Stimmung, Interessenverlust, Antriebsminderung. Keine Suizidgedanken, Alltagsfunktion meist erhalten." },
  { code: 'F32.1', label: 'Mittelgradige depressive Episode', chapter: 'F', definition: "Mittelgradige depressive Episode mit mehreren typischen und zusätzlichen Symptomen. Betroffene haben meist erhebliche Schwierigkeiten, alltägliche Aktivitäten fortzuführen." },
  { code: 'F32.2', label: 'Schwere depressive Episode ohne psychotische Symptome', chapter: 'F', definition: "Schwere depressive Episode ohne psychotische Symptome. Starkes Leiden, Suizidgefahr, Alltagsfunktion meist nicht aufrechtzuerhalten." },
  { code: 'F32.3', label: 'Schwere depressive Episode mit psychotischen Symptomen', chapter: 'F' },
  { code: 'F32.8', label: 'Sonstige depressive Episoden', chapter: 'F' },
  { code: 'F32.9', label: 'Depressive Episode, nicht näher bezeichnet', chapter: 'F' },
  { code: 'F33', label: 'Rezidivierende depressive Störung', chapter: 'F' },
  { code: 'F33.0', label: 'Rezidivierende depressive Störung, gegenwärtig leichte Episode', chapter: 'F' },
  { code: 'F33.1', label: 'Rezidivierende depressive Störung, gegenwärtig mittelgradige Episode', chapter: 'F', definition: "Rezidivierende depressive Störung, gegenwärtig mittelgradige Episode. Mehrere frühere Episoden, aktuell mittelgradige Symptomatik." },
  { code: 'F33.2', label: 'Rezidivierende depressive Störung, gegenwärtig schwere Episode ohne psychotische Symptome', chapter: 'F' },
  { code: 'F33.3', label: 'Rezidivierende depressive Störung, gegenwärtig schwere Episode mit psychotischen Symptomen', chapter: 'F' },
  { code: 'F33.4', label: 'Rezidivierende depressive Störung, gegenwärtig remittiert', chapter: 'F', definition: "Rezidivierende depressive Störung, gegenwärtig remittiert: Frühere depressive Episoden, aktuell keine signifikanten depressiven Symptome." },
  { code: 'F34', label: 'Anhaltende affektive Störungen', chapter: 'F' },
  { code: 'F34.0', label: 'Zyklothymia', chapter: 'F', definition: "Zyklothymia: Chronische Stimmungsinstabilität mit mehreren Perioden milder Depression und Hypomanie über mindestens 2 Jahre." },
  { code: 'F34.1', label: 'Dysthymia', chapter: 'F', definition: "Dysthymia: Chronisch depressive Stimmung über mindestens 2 Jahre, weniger schwer als Episode. Beeinträchtigung der sozialen und beruflichen Funktionsfähigkeit." },
  { code: 'F38', label: 'Sonstige affektive Störungen', chapter: 'F' },
  { code: 'F39', label: 'Nicht näher bezeichnete affektive Störung', chapter: 'F' },

// ── F40–F48 Neurotische, Belastungs- und somatoforme Störungen ───────────────
  { code: 'F40', label: 'Phobische Störungen', chapter: 'F' },
  { code: 'F40.0', label: 'Agoraphobie', chapter: 'F' },
  { code: 'F40.00', label: 'Agoraphobie ohne Panikstörung', chapter: 'F' },
  { code: 'F40.01', label: 'Agoraphobie mit Panikstörung', chapter: 'F' },
  { code: 'F40.1', label: 'Soziale Phobien', chapter: 'F', definition: "Soziale Phobie: Angst vor Beobachtung durch andere Menschen, Vermeidung sozialer Situationen. Furcht vor peinlichem oder beschämendem Verhalten." },
  { code: 'F40.2', label: 'Spezifische (isolierte) Phobien', chapter: 'F' },
  { code: 'F41', label: 'Andere Angststörungen', chapter: 'F' },
  { code: 'F41.0', label: 'Panikstörung (episodisch paroxysmale Angst)', chapter: 'F', definition: "Panikstörung: Wiederkehrende unerwartete Panikattacken mit vegetativen Symptomen, Entfremdungsgefühlen, Todesangst. Keine spezifische Auslösesituation." },
  { code: 'F41.1', label: 'Generalisierte Angststörung', chapter: 'F', definition: "Generalisierte Angststörung: Anhaltende, freifließende Angst, Sorgen über viele Lebensbereiche, Anspannung, Schlafstörungen, Konzentrationsprobleme." },
  { code: 'F41.2', label: 'Angst und depressive Störung, gemischt', chapter: 'F' },
  { code: 'F41.3', label: 'Andere gemischte Angststörungen', chapter: 'F' },
  { code: 'F42', label: 'Zwangsstörung', chapter: 'F' },
  { code: 'F42.0', label: 'Vorwiegend Zwangsgedanken oder Grübelzwang', chapter: 'F' },
  { code: 'F42.1', label: 'Vorwiegend Zwangshandlungen (Zwangsrituale)', chapter: 'F' },
  { code: 'F42.2', label: 'Zwangsgedanken und -handlungen, gemischt', chapter: 'F', definition: "Zwangsstörung mit gemischten Zwangsgedanken und -handlungen: Sowohl Gedanken als auch Rituale vorhanden, beide gleich belastend." },
  { code: 'F43', label: 'Reaktionen auf schwere Belastungen und Anpassungsstörungen', chapter: 'F' },
  { code: 'F43.0', label: 'Akute Belastungsreaktion', chapter: 'F', definition: "Akute Belastungsreaktion nach außergewöhnlicher körperlicher oder psychischer Belastung. Symptome klingen innerhalb von Stunden bis Tagen ab." },
  { code: 'F43.1', label: 'Posttraumatische Belastungsstörung', chapter: 'F', definition: "PTBS: Verzögerte oder anhaltende Reaktion auf ein belastendes Ereignis. Intrusionen, Vermeidung, Hyperarousal, emotionale Taubheit." },
  { code: 'F43.2', label: 'Anpassungsstörungen', chapter: 'F', definition: "Anpassungsstörung: Emotionale oder Verhaltenssymptome als Reaktion auf identifizierbaren Stressor. Beginn innerhalb eines Monats nach dem Stressor." },
  { code: 'F43.20', label: 'Anpassungsstörung – Kurze depressive Reaktion', chapter: 'F' },
  { code: 'F43.21', label: 'Anpassungsstörung – Längere depressive Reaktion', chapter: 'F' },
  { code: 'F43.22', label: 'Anpassungsstörung – Angst und depressive Reaktion, gemischt', chapter: 'F' },
  { code: 'F44', label: 'Dissoziative Störungen (Konversionsstörungen)', chapter: 'F' },
  { code: 'F44.0', label: 'Dissoziative Amnesie', chapter: 'F' },
  { code: 'F44.1', label: 'Dissoziative Fugue', chapter: 'F', definition: "Dissoziative Fugue: Plötzliche unerwartete Reise, verbunden mit Amnesie für die eigene Vergangenheit und teilweiser oder vollständiger Identitätsverwirrung." },
  { code: 'F44.2', label: 'Dissoziativer Stupor', chapter: 'F' },
  { code: 'F44.3', label: 'Trance- und Besessenheitszustände', chapter: 'F' },
  { code: 'F44.4', label: 'Dissoziative Bewegungsstörungen', chapter: 'F' },
  { code: 'F44.5', label: 'Dissoziative Krampfanfälle', chapter: 'F' },
  { code: 'F44.6', label: 'Dissoziative Sensibilitäts- und Empfindungsstörungen', chapter: 'F' },
  { code: 'F44.7', label: 'Dissoziative Störungen, gemischt', chapter: 'F' },
  { code: 'F45', label: 'Somatoforme Störungen', chapter: 'F' },
  { code: 'F45.0', label: 'Somatisierungsstörung', chapter: 'F' },
  { code: 'F45.1', label: 'Undifferenzierte Somatisierungsstörung', chapter: 'F' },
  { code: 'F45.2', label: 'Hypochondrische Störung', chapter: 'F' },
  { code: 'F45.3', label: 'Somatoforme autonome Funktionsstörung', chapter: 'F' },
  { code: 'F45.4', label: 'Anhaltende somatoforme Schmerzstörung', chapter: 'F', definition: "Anhaltende somatoforme Schmerzstörung: Anhaltender schwerer Schmerz, der durch physiologische Prozesse nicht vollständig erklärt werden kann." },
  { code: 'F45.41', label: 'Chronische Schmerzstörung mit somatischen und psychischen Faktoren', chapter: 'F' },
  { code: 'F48', label: 'Andere neurotische Störungen', chapter: 'F' },
  { code: 'F48.0', label: 'Neurasthenie', chapter: 'F' },
  { code: 'F48.1', label: 'Depersonalisations- und Derealisationssyndrom', chapter: 'F' },

// ── F50–F59 Verhaltensauffälligkeiten mit körperlichen Störungen ─────────────
  { code: 'F50', label: 'Essstörungen', chapter: 'F' },
  { code: 'F50.0', label: 'Anorexia nervosa', chapter: 'F', definition: "Anorexia nervosa: Absichtlicher Gewichtsverlust, Körperschemastörung, Amenorrhoe. BMI unter 17,5. Lebensbedrohlich bei schwerem Verlauf." },
  { code: 'F50.1', label: 'Atypische Anorexia nervosa', chapter: 'F' },
  { code: 'F50.2', label: 'Bulimia nervosa', chapter: 'F', definition: "Bulimia nervosa: Wiederholte Episoden von Essattacken mit anschließendem Erbrechen oder anderen kompensatorischen Maßnahmen. Körpergewicht meist normal." },
  { code: 'F50.3', label: 'Atypische Bulimia nervosa', chapter: 'F' },
  { code: 'F50.4', label: 'Essattacken bei anderen psychischen Störungen', chapter: 'F' },
  { code: 'F51', label: 'Nicht organische Schlafstörungen', chapter: 'F' },
  { code: 'F51.0', label: 'Nicht organische Insomnie', chapter: 'F' },
  { code: 'F51.1', label: 'Nicht organische Hypersomnie', chapter: 'F' },
  { code: 'F52', label: 'Sexuelle Funktionsstörungen, nicht verursacht durch eine organische Störung', chapter: 'F' },
  { code: 'F54', label: 'Psychologische Faktoren oder Verhaltensfaktoren bei andernorts klassifizierten Krankheiten', chapter: 'F' },

// ── F60–F69 Persönlichkeits- und Verhaltensstörungen ────────────────────────
  { code: 'F60', label: 'Spezifische Persönlichkeitsstörungen', chapter: 'F' },
  { code: 'F60.0', label: 'Paranoide Persönlichkeitsstörung', chapter: 'F', definition: "Paranoide Persönlichkeitsstörung: Misstrauen, Empfindlichkeit gegenüber Zurückweisung, Neigung zur Feindseligkeit und Streitsucht." },
  { code: 'F60.1', label: 'Schizoide Persönlichkeitsstörung', chapter: 'F' },
  { code: 'F60.2', label: 'Dissoziale Persönlichkeitsstörung', chapter: 'F' },
  { code: 'F60.3', label: 'Emotional instabile Persönlichkeitsstörung', chapter: 'F', definition: "Emotional instabile Persönlichkeitsstörung: Impulsivität, instabile Stimmung und Beziehungen. Impulsiver Typ ohne Borderline-Merkmale." },
  { code: 'F60.30', label: 'Emotional instabile Persönlichkeitsstörung – Impulsiver Typ', chapter: 'F' },
  { code: 'F60.31', label: 'Emotional instabile Persönlichkeitsstörung – Borderline-Typ', chapter: 'F', definition: "Borderline-Persönlichkeitsstörung: Instabilität in Beziehungen, Selbstbild und Affekten, Impulsivität. Ausgeprägte Angst vor Verlassenwerden." },
  { code: 'F60.4', label: 'Histrionische Persönlichkeitsstörung', chapter: 'F' },
  { code: 'F60.5', label: 'Anankastische Persönlichkeitsstörung', chapter: 'F' },
  { code: 'F60.6', label: 'Ängstliche (vermeidende) Persönlichkeitsstörung', chapter: 'F' },
  { code: 'F60.7', label: 'Abhängige (asthenische) Persönlichkeitsstörung', chapter: 'F' },
  { code: 'F60.8', label: 'Sonstige spezifische Persönlichkeitsstörungen', chapter: 'F' },
  { code: 'F60.9', label: 'Persönlichkeitsstörung, nicht näher bezeichnet', chapter: 'F' },
  { code: 'F61', label: 'Kombinierte und andere Persönlichkeitsstörungen', chapter: 'F' },
  { code: 'F62', label: 'Andauernde Persönlichkeitsänderungen, nicht Folge einer Schädigung des Gehirns', chapter: 'F' },
  { code: 'F62.0', label: 'Andauernde Persönlichkeitsänderung nach Extrembelastung', chapter: 'F' },
  { code: 'F63', label: 'Abnorme Gewohnheiten und Störungen der Impulskontrolle', chapter: 'F' },
  { code: 'F63.0', label: 'Pathologisches Spielen', chapter: 'F' },
  { code: 'F63.1', label: 'Pathologische Brandstiftung (Pyromanie)', chapter: 'F' },
  { code: 'F63.2', label: 'Pathologisches Stehlen (Kleptomanie)', chapter: 'F' },
  { code: 'F64', label: 'Störungen der Geschlechtsidentität', chapter: 'F' },
  { code: 'F65', label: 'Störungen der Sexualpräferenz', chapter: 'F' },
  { code: 'F66', label: 'Psychische und Verhaltensstörungen in Verbindung mit der Sexualentwicklung', chapter: 'F' },
  { code: 'F68', label: 'Andere Persönlichkeits- und Verhaltensstörungen', chapter: 'F' },

// ── F70–F79 Intelligenzminderung ─────────────────────────────────────────────
  { code: 'F70', label: 'Leichte Intelligenzminderung', chapter: 'F' },
  { code: 'F71', label: 'Mittelgradige Intelligenzminderung', chapter: 'F' },
  { code: 'F72', label: 'Schwere Intelligenzminderung', chapter: 'F' },
  { code: 'F73', label: 'Schwerste Intelligenzminderung', chapter: 'F' },
  { code: 'F78', label: 'Andere Intelligenzminderung', chapter: 'F' },
  { code: 'F79', label: 'Nicht näher bezeichnete Intelligenzminderung', chapter: 'F' },

// ── F80–F89 Entwicklungsstörungen ────────────────────────────────────────────
  { code: 'F80', label: 'Umschriebene Entwicklungsstörungen des Sprechens und der Sprache', chapter: 'F' },
  { code: 'F81', label: 'Umschriebene Entwicklungsstörungen schulischer Fertigkeiten', chapter: 'F' },
  { code: 'F81.0', label: 'Lese- und Rechtschreibstörung', chapter: 'F' },
  { code: 'F81.2', label: 'Rechenstörung', chapter: 'F' },
  { code: 'F82', label: 'Umschriebene Entwicklungsstörung der motorischen Funktionen', chapter: 'F' },
  { code: 'F83', label: 'Kombinierte umschriebene Entwicklungsstörungen', chapter: 'F' },
  { code: 'F84', label: 'Tiefgreifende Entwicklungsstörungen', chapter: 'F' },
  { code: 'F84.0', label: 'Frühkindlicher Autismus', chapter: 'F', definition: "Frühkindlicher Autismus: Qualitative Beeinträchtigungen in sozialer Interaktion und Kommunikation, stereotype Verhaltensmuster. Beginn vor dem 3. Lebensjahr." },
  { code: 'F84.1', label: 'Atypischer Autismus', chapter: 'F' },
  { code: 'F84.2', label: 'Rett-Syndrom', chapter: 'F' },
  { code: 'F84.5', label: 'Asperger-Syndrom', chapter: 'F' },

// ── F90–F98 Verhaltens- und emotionale Störungen mit Beginn in der Kindheit ──
  { code: 'F90', label: 'Hyperkinetische Störungen', chapter: 'F' },
  { code: 'F90.0', label: 'Einfache Aktivitäts- und Aufmerksamkeitsstörung (ADHS)', chapter: 'F', definition: "ADHS: Aufmerksamkeitsdefizit-Hyperaktivitätsstörung. Unaufmerksamkeit, Hyperaktivität, Impulsivität, Beginn vor dem 7. Lebensjahr, situationsübergreifend." },
  { code: 'F90.1', label: 'Hyperkinetische Störung des Sozialverhaltens', chapter: 'F' },
  { code: 'F91', label: 'Störungen des Sozialverhaltens', chapter: 'F' },
  { code: 'F92', label: 'Kombinierte Störung des Sozialverhaltens und der Emotionen', chapter: 'F' },
  { code: 'F93', label: 'Emotionale Störungen des Kindesalters', chapter: 'F' },
  { code: 'F93.0', label: 'Emotionale Störung mit Trennungsangst des Kindesalters', chapter: 'F' },
  { code: 'F94', label: 'Störungen sozialer Funktionen mit Beginn in der Kindheit', chapter: 'F' },
  { code: 'F94.0', label: 'Elektiver Mutismus', chapter: 'F' },
  { code: 'F95', label: 'Ticstörungen', chapter: 'F' },
  { code: 'F95.2', label: 'Kombinierte vokale und multiple motorische Tics (Tourette-Syndrom)', chapter: 'F' },
  { code: 'F98', label: 'Andere Verhaltens- und emotionale Störungen mit Beginn in der Kindheit', chapter: 'F' },
  { code: 'F98.0', label: 'Nicht organische Enuresis', chapter: 'F' },
  { code: 'F98.1', label: 'Nicht organische Enkopresis', chapter: 'F' },
  { code: 'F99', label: 'Nicht näher bezeichnete psychische Störung', chapter: 'F' },

// ── Z-Codes (häufig in Psychotherapie) ──────────────────────────────────────
  { code: 'Z03.2', label: 'Beobachtung bei Verdacht auf psychische Störungen und Verhaltensstörungen', chapter: 'Z' },
  { code: 'Z04.6', label: 'Allgemeine psychiatrische Untersuchung, andernorts nicht klassifiziert', chapter: 'Z' },
  { code: 'Z09.3', label: 'Nachuntersuchung nach Psychotherapie', chapter: 'Z' },
  { code: 'Z13.3', label: 'Spezielle Untersuchung auf psychische Störungen und Verhaltensstörungen', chapter: 'Z' },
  { code: 'Z50.4', label: 'Psychotherapie, andernorts nicht klassifiziert', chapter: 'Z' },
  { code: 'Z54.3', label: 'Rekonvaleszenz nach Psychotherapie', chapter: 'Z' },
  { code: 'Z60.0', label: 'Probleme in Zusammenhang mit der Lebensphase', chapter: 'Z' },
  { code: 'Z60.4', label: 'Soziale Ausgrenzung und Ablehnung', chapter: 'Z' },
  { code: 'Z61', label: 'Probleme in Zusammenhang mit negativen Kindheitserlebnissen', chapter: 'Z' },
  { code: 'Z61.0', label: 'Verlust einer Bezugsperson in der Kindheit', chapter: 'Z' },
  { code: 'Z61.4', label: 'Sexueller Missbrauch in der Kindheit durch eine Person außerhalb der Primärfamilie', chapter: 'Z' },
  { code: 'Z61.5', label: 'Körperlicher Missbrauch in der Kindheit', chapter: 'Z' },
  { code: 'Z63.0', label: 'Probleme in der Beziehung zum Ehepartner oder Partner', chapter: 'Z' },
  { code: 'Z63.4', label: 'Verschwinden oder Tod eines Familienmitglieds', chapter: 'Z' },
  { code: 'Z65.5', label: 'Opfer von Folter', chapter: 'Z' },
  { code: 'Z71.4', label: 'Alkoholmissbrauchsberatung und -überwachung', chapter: 'Z' },
  { code: 'Z73.0', label: 'Ausgebranntsein (Burn-out)', chapter: 'Z', definition: "Burn-out: Zustand totaler Erschöpfung, Ausbrennen. Chronischer Arbeitsstress der nicht erfolgreich bewältigt wurde." },
  { code: 'Z73.1', label: 'Akzentuierung von Persönlichkeitszügen', chapter: 'Z' },
  { code: 'Z73.3', label: 'Belastung durch Anforderungen des Lebens, die keiner anderen Klassifikation bedürfen', chapter: 'Z' },
  { code: 'Z76.0', label: 'Wiederholung einer Verschreibung', chapter: 'Z' },
]

export function searchICD10(query: string, limit = 20): ICD10Code[] {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase().trim()
  const results: ICD10Code[] = []
  // Exact code match first
  for (const c of ICD10_CODES) {
    if (c.code.toLowerCase().startsWith(q)) results.push(c)
    if (results.length >= limit) return results
  }
  // Then label match
  for (const c of ICD10_CODES) {
    if (!results.includes(c) && c.label.toLowerCase().includes(q)) results.push(c)
    if (results.length >= limit) return results
  }
  return results
}
